import{i as p,a as y,S as $}from"./assets/vendor-38cc1e54.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(r){if(r.ep)return;r.ep=!0;const a=o(r);fetch(r.href,a)}})();const s={info:"Please enter a value in the search field!",endOfSearch:"We're sorry, but you've reached the end of search results.",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there are no connection to the server. Please try again later! ",exception:"Exception: We have some issue with connection. Please try again later! "},i={green:"#59a10d",orange:"#ffa000",red:"#ef4040"};function l(e,t){p.info({position:"topRight",backgroundColor:`${t}`,message:`${e}`})}y.defaults.baseURL="https://pixabay.com/api/";const M="45418693-8ae3627eda45814ae2d20cf49";async function m(e,t){const o={key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{return(await y.get("",{params:o})).data}catch(n){return n.response?l(s.error,i.orange):l(`${s.exception} ERROR:  ${n.message}`,i.orange),null}}const b=new $(".gallery a",{captionsData:"alt",captionDelay:250});function S(e,t,o=!1){const n=O(e);o?t.insertAdjacentHTML("beforeend",n):t.innerHTML=n,b.refresh()}function O(e){return e.hits.map(({webformatURL:t,largeImageURL:o,tags:n,likes:r,views:a,comments:c,downloads:E})=>`
            <li class="gallery-item hvr-grow">
                <a class="gallery-link" href="${o}">
                    <figure class="gallery-figure ">
                        <img class="gallery-image" src="${t}" alt="${n}" loading="lazy">
                        <figcaption class="gallery-figcaption">
                            <ul class="img-content-wrapper">
                                <li>Likes<span>${r}</span></li>
                                <li>Views<span>${a}</span></li>
                                <li>Comments<span>${c}</span></li>
                                <li>Downloads<span>${E}</span></li>
                            </ul>
                        </figcaption>
                    </figure>
                </a>
            </li>
          `).join("")}function L(e){return e?e&&e.totalHits===0?(showInfoMessage(MESSAGES.warning,MESSAGES_BG_COLORS.red),gallery.innerHTML="",!1):!0:(gallery.innerHTML="",!1)}const v=document.querySelector(".search-form"),g=document.querySelector(".gallery"),f=document.querySelector(".load-more");let d="",u=1;v.addEventListener("submit",P);f.addEventListener("click",q);async function P(e){if(e.preventDefault(),p.destroy(),g.innerHTML="",w(),d=new FormData(e.target).get("search").trim(),!d){l(s.info,i.red),h();return}u=1,f.classList.add("is-hidden");try{const o=await m(d,u);L(o)&&(S(o,g),f.classList.remove("is-hidden"))}catch(o){l(s.exception+o,i.orange)}finally{h(),e.target.reset()}}async function q(){u+=1,w();try{const e=await m(d,u);L(e)&&(S(e,g,!0),x()),e.hits.length<15&&(f.classList.add("is-hidden"),l(s.endOfSearch,i.orange))}catch(e){l(s.exception+e,i.orange)}finally{h()}}function x(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function w(){const e=document.querySelector(".loader");e&&e.classList.remove("is-hidden")}function h(){const e=document.querySelector(".loader");e&&e.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
