import{i as y,a as m,S as $}from"./assets/vendor-38cc1e54.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const s={info:"Please enter a value in the search field!",endOfSearch:"We're sorry, but you've reached the end of search results.",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there are no connection to the server. Please try again later! ",exception:"Exception: We have some issue with connection. Please try again later! "},i={green:"#59a10d",orange:"#ffa000",red:"#ef4040"};function l(e,t){y.info({position:"topRight",backgroundColor:`${t}`,message:`${e}`})}m.defaults.baseURL="https://pixabay.com/api/";const O="45418693-8ae3627eda45814ae2d20cf49";async function p(e,t){const a={key:O,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};try{return(await m.get("",{params:a})).data}catch(n){return n.response?l(s.error,i.orange):l(`${s.exception} ERROR:  ${n.message}`,i.orange),null}}const b=new $(".gallery a",{captionsData:"alt",captionDelay:250});function S(e,t,a=!1){const n=v(e);a?t.insertAdjacentHTML("beforeend",n):t.innerHTML=n,b.refresh()}function v(e){return e.hits.map(({webformatURL:t,largeImageURL:a,tags:n,likes:r,views:o,comments:c,downloads:E})=>`
            <li class="gallery-item hvr-grow">
                <a class="gallery-link" href="${a}">
                    <figure class="gallery-figure ">
                        <img class="gallery-image" src="${t}" alt="${n}" loading="lazy">
                        <figcaption class="gallery-figcaption">
                            <ul class="img-content-wrapper">
                                <li>Likes<span>${r}</span></li>
                                <li>Views<span>${o}</span></li>
                                <li>Comments<span>${c}</span></li>
                                <li>Downloads<span>${E}</span></li>
                            </ul>
                        </figcaption>
                    </figure>
                </a>
            </li>
          `).join("")}function L(e){return e?e&&e.totalHits===0?(showInfoMessage(MESSAGES.warning,MESSAGES_BG_COLORS.red),gallery.innerHTML="",!1):!0:(gallery.innerHTML="",!1)}const P=document.querySelector(".search-form"),g=document.querySelector(".gallery"),u=document.querySelector(".load-more");let f="",d=1;P.addEventListener("submit",q);u.addEventListener("click",x);async function q(e){if(e.preventDefault(),y.destroy(),g.innerHTML="",w(),f=new FormData(e.target).get("search").trim(),!f){l(s.info,i.red),h();return}d=1,u.classList.add("is-hidden");try{const a=await p(f,d);L(a)&&(S(a,g),a.totalHits>15?G():(M(),l(s.endOfSearch,i.orange)))}catch(a){l(s.exception+a,i.orange)}finally{h(),e.target.reset()}}async function x(){d+=1,w();try{const e=await p(f,d);L(e)&&(S(e,g,!0),D()),d*15>=e.totalHits&&(M(),l(s.endOfSearch,i.orange))}catch(e){l(s.exception+e,i.orange)}finally{h()}}function D(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function w(){const e=document.querySelector(".loader");e&&e.classList.remove("is-hidden")}function h(){const e=document.querySelector(".loader");e&&e.classList.add("is-hidden")}function G(){u.classList.remove("is-hidden")}function M(){u.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
